In [1]:
import pandas as pd
import numpy as np
import sys
import pickle
import glob
import os
import matplotlib.pyplot as plt

In [2]:
merged_df = pd.read_pickle('/Users/darylwilding-mcbride/Downloads/experiments/190719_Hela_Ecoli/training-sets/merged_df.pkl')
merged_df.head()

,file_idx,sequence,charge,run_mz,run_scan,run_rt,theoretical_mz,experiment_scan,experiment_rt,experiment_intensity,delta_mz,delta_scan,delta_rt
0,0,AAAAAAAAAPAAAATAPTTAATTAATAAQ,2,1184.608424,74.065131,601.582008,1184.1049,73.911301,602.012681,108754.444444,-0.503524,-0.153831,0.430673
1,0,AAAAAAAAVPSAGPAGPAPTSAAGR,2,1016.532311,156.625361,486.692475,1016.0286,160.291329,489.973155,58456.622222,-0.503711,3.665967,3.280680
2,0,AAAAAWEEPSSGNGTAR,2,823.382064,535.310000,367.240000,822.8783,533.861853,371.271659,277023.690476,-0.503764,-1.448147,4.031659
3,0,AAAAPVTGPLADDPIQETITFDDFAK,3,892.112987,468.100000,997.180000,891.7775,465.668232,997.391366,150202.950000,-0.335487,-2.431768,0.211366
4,0,AAAEDVNVTFEDQQK,2,832.891998,485.630000,471.790000,832.3878,487.082550,475.841292,116982.693430,-0.504198,1.452550,4.051292

In [ ]:
run_sequences_l = []
for group_name,group_df in merged_df.groupby(['file_idx','sequence','charge'], as_index=False):