In [3]:
import pandas as pd
import numpy as np
import sqlite3
import json
import matplotlib.pyplot as plt

In [4]:
EXPERIMENT_DIR = '/home/ubuntu/experiments/dwm-test'
EXTRACTED_FEATURES_DIR = "{}/extracted-features".format(EXPERIMENT_DIR)
EXTRACTED_FEATURES_DB_NAME = "{}/extracted-features.sqlite".format(EXTRACTED_FEATURES_DIR)

In [5]:
db_conn = sqlite3.connect(EXTRACTED_FEATURES_DB_NAME)
sequences_df = pd.read_sql_query('select * from features limit 1', db_conn)
db_conn.close()

In [6]:
sequences_df.columns

Index(['sequence', 'charge', 'file_idx', 'peak_idx', 'target_coords',
       'theoretical_mz', 'q_value', 'delta_mz_ppm', 'delta_rt', 'delta_scan',
       'fwhm_rt_0', 'fwhm_scan_0', 'geometric_mean_0_1',
       'geometric_mean_0_1_2', 'isotope_0_1_mz_delta_ppm',
       'isotope_0_1_rt_delta', 'isotope_0_1_scan_delta',
       'isotope_0_2_mz_delta_ppm', 'isotope_0_2_rt_delta',
       'isotope_0_2_scan_delta', 'monoisotope_auc_over_isotope_peak_auc_sum',
       'monoisotope_int_over_isotope_peak_int_sum', 'mz_delta_ppm_std_dev_0',
       'mz_delta_ppm_std_dev_1', 'number_of_frames_0', 'number_of_frames_1',
       'number_of_frames_2', 'number_of_missing_frames_0',
       'number_of_missing_frames_1', 'number_of_missing_frames_2',
       'peak_base_width_rt_0', 'peak_base_width_scan_0', 'r_squared_phr',
       'rt_isotope_correlation', 'rt_peak_symmetry_0', 'rt_peak_symmetry_1',
       'rt_peak_symmetry_2', 'scan_isotope_correlation',
       'scan_peak_symmetry_0', 'scan_peak_symmetry_1', 'scan_peak_symmetry_2',
       'classed_as', 'inferred', 'intensity', 'isotope_1_filtered_points_l',
       'isotope_1_rt_bounds', 'isotope_2_filtered_points_l',
       'isotope_2_rt_bounds', 'isotope_idx_not_in_saturation',
       'isotope_intensities_l', 'mono_filtered_points_l', 'mono_raw_points_l',
       'mono_rt_bounds', 'monoisotopic_mass', 'monoisotopic_mz_centroid',
       'number_of_isotopes', 'rt_apex', 'scan_apex', 'run_name', 'batch',
       'human', 'number_of_runs_extracted'],
      dtype='object')

In [37]:
db_conn = sqlite3.connect(EXTRACTED_FEATURES_DB_NAME)
sequences_df = pd.read_sql_query('select sequence,charge,intensity,isotope_intensities_l,inferred,isotope_idx_not_in_saturation,number_of_isotopes from features', db_conn)
db_conn.close()

In [38]:
sequences_df

,sequence,charge,intensity,isotope_intensities_l,inferred,isotope_idx_not_in_saturation,number_of_isotopes
0,REEESAAAAEVEER,2,67438,"[[55491.0, true, 67438.0, true, [[788.36574426...",1,4,7
1,REEESAAAAEVEER,2,52776,"[[43751.0, true, 52776.0, true, [[788.36573569...",1,3,7
2,REEESAAAAEVEER,2,49032,"[[41837.0, true, 49032.0, true, [[788.36568009...",1,3,7
3,REEESAAAAEVEER,2,77353,"[[60401.0, true, 77353.0, true, [[788.36561905...",1,4,7
4,REEESAAAAEVEER,2,70321,"[[62856.0, true, 70321.0, true, [[788.36561435...",1,4,7
5,REEESAAAAEVEER,2,60514,"[[55491.0, true, 60514.0, true, [[788.36574021...",1,4,7
6,REEESAAAAEVEER,2,47762,"[[38395.0, true, 47762.0, true, [[788.36567767...",1,3,7
7,REEESAAAAEVEER,2,57630,"[[60401.0, true, 57630.0, true, [[788.36561917...",1,3,7
8,REEESAAAAEVEER,2,48280,"[[41837.0, true, 48280.0, true, [[788.36573078...",1,3,7
9,REEESAAAAEVEER,2,59031,"[[57946.0, true, 59031.0, true, [[788.36567875...",1,3,7
10,REEESAAAAEVEER,2,52652,"[[41837.0, true, 52652.0, true, [[788.36570724...",1,3,7
11,REEESAAAAEVEER,2,50798,"[[38265.0, true, 50798.0, true, [[788.36572435...",1,3,7
12,REEESAAAAEVEER,2,58060,"[[62856.0, true, 58060.0, true, [[788.36561610...",1,3,7
13,REEESAAAAEVEER,2,61235,"[[60401.0, true, 61235.0, true, [[788.36561648...",1,3,7
14,REEESAAAAEVEER,2,69998,"[[55491.0, true, 69998.0, true, [[788.36564127...",1,4,7
15,REEESAAAAEVEER,2,53776,"[[41837.0, true, 53776.0, true, [[788.36571777...",1,3,7
16,REEESAAAAEVEER,2,46288,"[[40051.0, true, 46288.0, true, [[788.36568448...",1,3,7
17,REEESAAAAEVEER,2,67357,"[[57946.0, true, 67357.0, true, [[788.36570780...",1,4,7
18,REEESAAAAEVEER,2,49499,"[[38265.0, true, 49499.0, true, [[788.36572485...",1,3,7
19,REEESAAAAEVEER,2,48959,"[[43751.0, true, 48959.0, true, [[788.36571238...",1,3,7
20,VTIAQGGVLPNIQAVLLPK,2,54679,"[[44916.0, true, 54679.0, true, [[966.08403731...",1,4,7
21,VTIAQGGVLPNIQAVLLPK,2,63474,"[[48122.0, true, 63474.0, true, [[966.08396199...",1,4,7
22,VTIAQGGVLPNIQAVLLPK,2,53944,"[[48122.0, true, 53944.0, true, [[966.08398114...",1,4,7
23,VTIAQGGVLPNIQAVLLPK,2,62649,"[[43368.0, true, 62649.0, true, [[966.08388501...",1,4,7
24,VTIAQGGVLPNIQAVLLPK,2,61849,"[[39930.0, true, 61849.0, true, [[966.08388035...",1,4,7
25,VTIAQGGVLPNIQAVLLPK,2,56497,"[[43368.0, true, 56497.0, true, [[966.08403658...",1,4,7
26,VTIAQGGVLPNIQAVLLPK,2,58341,"[[57288.0, true, 58341.0, true, [[966.08398772...",1,4,7
27,VTIAQGGVLPNIQAVLLPK,2,60908,"[[43368.0, true, 60908.0, true, [[966.08389032...",1,4,7
28,VTIAQGGVLPNIQAVLLPK,2,65370,"[[51560.0, true, 65370.0, true, [[966.08402522...",1,4,7
29,VTIAQGGVLPNIQAVLLPK,2,60675,"[[43026.0, true, 60675.0, true, [[966.08388642...",1,4,7
30,VTIAQGGVLPNIQAVLLPK,2,61978,"[[54424.0, true, 61978.0, true, [[966.08402429...",1,4,7
31,VTIAQGGVLPNIQAVLLPK,2,57709,"[[48696.0, true, 57709.0, true, [[966.08399931...",1,4,7
32,VTIAQGGVLPNIQAVLLPK,2,60172,"[[46806.0, true, 60172.0, true, [[966.08388013...",1,4,7
33,VTIAQGGVLPNIQAVLLPK,2,55607,"[[48696.0, true, 55607.0, true, [[966.08387983...",1,4,7
34,VTIAQGGVLPNIQAVLLPK,2,60069,"[[46806.0, true, 60069.0, true, [[966.08397513...",1,4,7
35,VTIAQGGVLPNIQAVLLPK,2,64493,"[[57288.0, true, 64493.0, true, [[966.08400084...",1,4,7
36,VTIAQGGVLPNIQAVLLPK,2,60198,"[[54424.0, true, 60198.0, true, [[966.08396454...",1,4,7
37,VTIAQGGVLPNIQAVLLPK,2,62674,"[[39930.0, true, 62674.0, true, [[966.08392152...",1,4,7
38,VTIAQGGVLPNIQAVLLPK,2,61810,"[[57288.0, true, 61810.0, true, [[966.08399363...",1,4,7
39,VTIAQGGVLPNIQAVLLPK,2,62352,"[[57288.0, true, 62352.0, true, [[966.08400222...",1,4,7

In [11]:
sequences_df.isotope_idx_not_in_saturation.unique()

array([4, 3])

In [26]:
s = sequences_df.iloc[10]
s

sequence                                                            REEESAAAAEVEER
charge                                                                           2
intensity                                                                    52652
isotope_intensities_l            [[41837.0, true, 52652.0, true, [[788.36570724...
inferred                                                                         1
isotope_idx_not_in_saturation                                                    3
Name: 10, dtype: object

In [27]:
isotope_intensities_l = json.loads(s.isotope_intensities_l)

In [28]:
cols = ['summed_intensity','saturated','inferred_intensity','inferred','isotope_points','isotope_apex_points']

In [29]:
isotope_intensities_df = pd.DataFrame(isotope_intensities_l, columns=cols)

In [30]:
isotope_intensities_df

,summed_intensity,saturated,inferred_intensity,inferred,isotope_points,isotope_apex_points
0,41837.0,True,52652.0,True,"[[788.3657072420101, 519.0, 2511.0, 265.621418...","[[788.3657072420101, 584.0, 2511.0, 265.621418..."
1,31760.0,True,44639.0,True,"[[788.8677343738383, 521.0, 2511.0, 265.621418...","[[788.8677343738383, 573.0, 2511.0, 265.621418..."
2,19555.0,True,21115.0,True,"[[789.3655154587753, 519.0, 2511.0, 265.621418...","[[789.3699213019812, 579.0, 2511.0, 265.621418..."
3,7214.0,False,7214.0,False,"[[789.8678607815052, 537.0, 2506.0, 265.093187...","[[789.8678607815052, 576.0, 2511.0, 265.621418..."
4,2229.0,False,2229.0,False,"[[790.3703659005386, 532.0, 2506.0, 265.093187...","[[790.3703659005386, 582.0, 2511.0, 265.621418..."
5,657.0,False,657.0,False,"[[790.8730308158699, 546.0, 2506.0, 265.093187...","[[790.8774408642412, 583.0, 2511.0, 265.621418..."
6,285.0,False,285.0,False,"[[791.3758557986072, 523.0, 2426.0, 256.643906...","[[791.3758557986072, 523.0, 2426.0, 256.643906..."

In [31]:
isotope_intensities_df.iloc[0].isotope_apex_points

[[788.3657072420101, 584.0, 2511.0, 265.6214181883868, 14541.0],
 [788.3657072420101, 581.0, 2516.0, 266.15017510980715, 14541.0],
 [788.3657082580164, 584.0, 2521.0, 266.6771731209893, 12755.0]]

In [32]:
isotope_intensities_df.iloc[1].isotope_apex_points

[[788.8677343738383, 573.0, 2511.0, 265.6214181883868, 11096.0],
 [788.8677343738383, 573.0, 2516.0, 266.15017510980715, 11096.0],
 [788.8677353904912, 582.0, 2521.0, 266.6771731209893, 9568.0]]

In [33]:
isotope_intensities_df.iloc[2].isotope_apex_points

[[789.3699213019812, 579.0, 2511.0, 265.6214181883868, 6899.0],
 [789.3699213019812, 577.0, 2516.0, 266.15017510980715, 6899.0],
 [789.3699223192815, 582.0, 2521.0, 266.6771731209893, 5757.0]]

In [34]:
isotope_intensities_df.iloc[3].isotope_apex_points

[[789.8678607815052, 576.0, 2511.0, 265.6214181883868, 2207.0],
 [789.8722680264326, 576.0, 2516.0, 266.15017510980715, 2722.0],
 [789.8678617994474, 586.0, 2521.0, 266.6771731209893, 2285.0]]

In [35]:
isotope_intensities_df.iloc[4].isotope_apex_points

[[790.3703659005386, 582.0, 2511.0, 265.6214181883868, 625.0],
 [790.3703659005386, 571.0, 2516.0, 266.15017510980715, 771.0],
 [790.3703669191282, 597.0, 2521.0, 266.6771731209893, 833.0]]