In [1]:
import pandas as pd
import sqlite3
import numpy as np
import matplotlib.pyplot as plt

In [24]:
mscypher_filename = "/home/ubuntu/UPS2_allion/MSCypher.txt"
mscypher_df = pd.read_table(mscypher_filename, sep="\t", dtype="str", engine='python')
feature_id=4
DB_NAME = "/home/ubuntu/UPS2_allion/UPS2_allion-features-1-1097.sqlite"

In [25]:
# convert the numeric fields and sort the features by their score
mscypher_df = mscypher_df.apply(pd.to_numeric, errors='ignore').sort_values(by=['FeatureNum','DiggerPepScore'], ascending=False)

In [26]:
# remove feature-duplicates from the MSC output, keeping the highest score
mscypher_df.drop_duplicates(subset=['FeatureNum'], keep='first', inplace=True)

In [27]:
mscypher_df.head()

,QueryNum,Target,Rank,NumPrecMatches,PepIDConsensus,PepPIF,MS2PIF,NumScoringFragIonMatches,NumScoringFragIonPeaks,PercentSimilarity,...,EndPos,PreRes,PostRes,EnzymeSpecificity,ProteinLength,AccNums,FastaEntryNum,UniqueID,deltaCn,XCorr
15158,15031,Target,1,0,30,0.0,0.0,0,0,-1.0,...,nan,nan,nan,nan,nan,nan,nan,21019,-1.0,0.0
5484,5420,Target,1,0,30,0.0,0.0,0,0,-1.0,...,nan,nan,nan,nan,nan,nan,nan,21018,-1.0,0.0
17443,17301,Target,1,0,30,0.0,0.0,0,0,-1.0,...,nan,nan,nan,nan,nan,nan,nan,21017,-1.0,0.0
16605,16465,Target,1,0,30,0.0,0.0,0,0,-1.0,...,nan,nan,nan,nan,nan,nan,nan,21016,-1.0,0.0
16592,16452,Target,1,0,30,0.0,0.0,0,0,-1.0,...,nan,nan,nan,nan,nan,nan,nan,21015,-1.0,0.0

In [28]:
len(mscypher_df)

19617

In [29]:
mscypher_df.columns.tolist()

['QueryNum',
 'Target',
 'Rank',
 'NumPrecMatches',
 'PepIDConsensus',
 'PepPIF',
 'MS2PIF',
 'NumScoringFragIonMatches',
 'NumScoringFragIonPeaks',
 'PercentSimilarity',
 'PepSeq',
 'deNovoSeq',
 'rnkScr',
 'pnvScr',
 'EludePepSeq',
 'VMLScore',
 'Mods',
 'NumMods',
 'NumPhosphos',
 'PhosphoMods',
 'DiggerPepScore',
 'DiggerPepHomologyScore',
 'PercolatorQValue',
 'PercolatorPEP',
 'FeatureIntensityAUC',
 'ObsRtMS2',
 'ObsRtApex',
 'PredRt',
 'MZ',
 'Charge',
 'ExpMassDa',
 'PepMassDa',
 'DeltaMassDa',
 'DeltaMassPPM',
 'C13',
 'NumDataPoints',
 'NumScans',
 'NumIsotopePeaks',
 'FileName',
 'MS2Scan',
 'RMSErrorPPM',
 'RMSErrorNumMatches',
 'TIC',
 'CompBondCleavage',
 'DeltaScore',
 'DeltaRt',
 'ChimericStatus',
 'FeatureNum',
 'MissedCleavages',
 'RPMS',
 'SVMScore',
 'SVMResult',
 'SVMSig',
 'RFFeatureScore',
 'RFPSMScore',
 'ModPepID',
 'Rawfilename',
 'RFRank',
 'RFFeatureFDR',
 'RFPsmFDR',
 'TargetVotes',
 'DecoyVotes',
 'RFPrediction',
 'MAErrorPPM',
 'AltDeltaScore',
 'FragMZ',
 'FragInt',
 'FragError',
 'FragIonTypes',
 'FragPos',
 'FragCharge',
 'a',
 'b',
 'b-18',
 'b-17',
 'b++',
 'b++-18',
 'b++-17',
 'y',
 'y-18',
 'y-17',
 'y++',
 'y++-18',
 'y++-17',
 'imm',
 'YB',
 'YA',
 'c',
 'c++',
 'z+1',
 'z+1++',
 'z+2',
 'z+2++',
 'Intensity a',
 'Intensity b',
 'Intensity b-18',
 'Intensity b-17',
 'Intensity b++',
 'Intensity b++-18',
 'Intensity b++-17',
 'Intensity y',
 'Intensity y-18',
 'Intensity y-17',
 'Intensity y++',
 'Intensity y++-18',
 'Intensity y++-17',
 'Intensity imm',
 'Intensity YB',
 'Intensity YA',
 'Intensity c',
 'Intensity c++',
 'Intensity z+1',
 'Intensity z+1++',
 'Intensity z+2',
 'Intensity z+2++',
 'Count a',
 'Count b',
 'Count b-18',
 'Count b-17',
 'Count b++',
 'Count b++-18',
 'Count b++-17',
 'Count y',
 'Count y-18',
 'Count y-17',
 'Count y++',
 'Count y++-18',
 'Count y++-17',
 'Count imm',
 'Count YB',
 'Count YA',
 'Count c',
 'Count c++',
 'Count z+1',
 'Count z+1++',
 'Count z+2',
 'Count z+2++',
 'StartPos',
 'EndPos',
 'PreRes',
 'PostRes',
 'EnzymeSpecificity',
 'ProteinLength',
 'AccNums',
 'FastaEntryNum',
 'UniqueID',
 'deltaCn',
 'XCorr']

In [30]:
msc_subset_df = mscypher_df[["DiggerPepScore", "FeatureNum", "FragMZ", "FragInt", "FragError", "FragIonTypes", "FragPos", "FragCharge", "DeltaMassDa", "DeltaMassPPM"]].copy()

In [31]:
msc_subset_df.head()

,DiggerPepScore,FeatureNum,FragMZ,FragInt,FragError,FragIonTypes,FragPos,FragCharge,DeltaMassDa,DeltaMassPPM
15158,0.0,21928,0.000000,0.000000,0.000000,x;x,0,0,0.0,0.0
5484,0.0,21927,0.000000,0.000000,0.000000,x;x,0,0,0.0,0.0
17443,0.0,21926,0.000000,0.000000,0.000000,x;x,0,0,0.0,0.0
16605,0.0,21925,0.000000,0.000000,0.000000,x;x,0,0,0.0,0.0
16592,0.0,21924,0.000000,0.000000,0.000000,x;x,0,0,0.0,0.0

In [32]:
msc_subset_df[msc_subset_df.FeatureNum==feature_id]

,DiggerPepScore,FeatureNum,FragMZ,FragInt,FragError,FragIonTypes,FragPos,FragCharge,DeltaMassDa,DeltaMassPPM
7570,320.189,4,277.156006;1466.756714;1448.741699;1449.729736...,867823.000000;4746105.000000;36308.015625;2408...,0.001343;-0.003052;-0.007568;-0.003540;-0.0091...,b;y;y*;y^;y;y;y*;y^;y;y^;b;y;y^;b;y;b;y;b;a;b;...,2;14;14;14;13;12;12;12;11;11;6;10;10;7;9;8;8;9...,1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;...,-0.007459,-4.282

In [33]:
db_conn = sqlite3.connect(DB_NAME)
ms2_peaks_df = pd.read_sql_query("select feature_id,peak_id,centroid_mz,intensity from ms2_peaks_within_window where feature_id={}".format(feature_id), db_conn)
db_conn.close()

In [34]:
ms2_peaks_df.head()

   feature_id  peak_id  centroid_mz  intensity
0           4        1      871.957  113612862
1           4        2      872.459  105172507
2           4        4      872.962   68061875
3           4        7      873.463   26440569
4           4        8      863.447   11095406

In [118]:
msc_fragments_df = pd.DataFrame([], columns=['FragMZ', 'FragInt', 'FragError', 'FragIonTypes', 'FragPos', 'FragCharge'])

In [119]:
msc_fragments_df

Empty DataFrame
Columns: [FragMZ, FragInt, FragError, FragIonTypes, FragPos, FragCharge]
Index: []

In [113]:
# break out the fragments reported by MSC for this feature
msc_fragments = msc_subset_df[msc_subset_df.FeatureNum==feature_id].iloc[0]
msc_fragments

DiggerPepScore                                              320.189
FeatureNum                                                        4
FragMZ            277.156006;1466.756714;1448.741699;1449.729736...
FragInt           867823.000000;4746105.000000;36308.015625;2408...
FragError         0.001343;-0.003052;-0.007568;-0.003540;-0.0091...
FragIonTypes      b;y;y*;y^;y;y;y*;y^;y;y^;b;y;y^;b;y;b;y;b;a;b;...
FragPos           2;14;14;14;13;12;12;12;11;11;6;10;10;7;9;8;8;9...
FragCharge        1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;...
DeltaMassDa                                              -0.0074586
DeltaMassPPM                                                 -4.282
Name: 7570, dtype: object

In [92]:
FragMZ = list(map(float, msc_fragments.FragMZ.split(';')))
FragInt = list(map(float, msc_fragments.FragInt.split(';')))
FragError = list(map(float, msc_fragments.FragError.split(';')))
FragIonTypes = list(map(str, msc_fragments.FragIonTypes.split(';')))
FragPos = list(map(int, msc_fragments.FragPos.split(';')))
FragCharge = list(map(int, msc_fragments.FragCharge.split(';')))

In [93]:
msc_fragments_df = pd.DataFrame(list(zip(FragMZ, FragInt, FragError, FragIonTypes, FragPos, FragCharge)), columns=['FragMZ', 'FragInt', 'FragError', 'FragIonTypes', 'FragPos', 'FragCharge'])

In [94]:
msc_fragments_df

         FragMZ       FragInt  FragError FragIonTypes  FragPos  FragCharge
0    277.156006  8.678230e+05   0.001343            b        2           1
1   1466.756714  4.746105e+06  -0.003052            y       14           1
2   1448.741699  3.630802e+04  -0.007568           y*       14           1
3   1449.729736  2.408630e+05  -0.003540           y^       14           1
4   1369.697876  1.210633e+06  -0.009155            y       13           1
5   1256.621948  8.328303e+06  -0.000977            y       12           1
6   1238.609985  8.315001e+04  -0.002441           y*       12           1
7   1239.598022  4.238690e+05   0.001587           y^       12           1
8   1185.584961  9.656905e+06  -0.000854            y       11           1
9   1168.561035  4.570460e+05   0.001709           y^       11           1
10   672.370972  5.319180e+06  -0.000549            b        6           1
11  1071.541992  6.934142e+06  -0.000977            y       10           1
12  1054.517944  1.781150e+05   0.001587           y^       10           1
13   729.393005  1.584804e+06   0.000000            b        7           1
14  1014.520996  2.201039e+06  -0.000427            y        9           1
15   843.437012  1.828656e+06   0.001099            b        8           1
16   900.476990  2.051110e+06  -0.001526            y        8           1
17   957.476990  1.459208e+06  -0.001892            b        9           1
18  1057.540039  8.030301e+04  -0.002441            a       10           1
19  1085.536987  3.627584e+06  -0.000488            b       10           1
20  1068.511963  9.996130e+05   0.001099           b^       10           1
21   658.375977  6.083308e+06  -0.001038            y        6           1
22  1144.572998  9.682501e+04  -0.001587            a       11           1
23  1172.568970  5.583050e+06  -0.000488            b       11           1
24  1155.546021  1.653730e+06   0.003052           b^       11           1
25  1269.614014  1.519560e+05  -0.008179            b       12           1
26  1251.609985  3.611601e+04  -0.001709           b*       12           1
27  1252.599976  2.341801e+04   0.004272           b^       12           1
28  1368.689941  2.237517e+06  -0.000732            b       13           1
29  1350.676880  3.367502e+04  -0.003174           b*       13           1
30  1351.664917  3.137270e+05   0.000854           b^       13           1
31   375.223999  1.898007e+06   0.000183            y        3           1
32  1483.716675  2.729554e+06  -0.000854            b       14           1
33   260.197998  9.366230e+05   0.001129            y        2           1
34  1596.801758  1.381216e+06   0.000122            b       15           1
35  1579.775757  2.100180e+05   0.000610           b^       15           1
36   815.421997  1.589597e+06   0.006775            y       15           2

In [120]:
# round the join column to match the ms2 peaks with the fragments reported by MSC
msc_fragments_df["FragMZ_round"] = msc_fragments_df.FragMZ.round(3)
ms2_peaks_df["centroid_mz_round"] = ms2_peaks_df.centroid_mz.round(3)

In [121]:
# match up the ms2 peaks with the fragments reported by MSC
ms2_peaks_msc_fragments_df = pd.merge(ms2_peaks_df, msc_fragments_df, how='left', left_on=['centroid_mz_round'], right_on=['FragMZ_round'])

In [122]:
ms2_peaks_msc_fragments_df

,feature_id,peak_id,centroid_mz,intensity,centroid_mz_round,FragMZ,FragInt,FragError,FragIonTypes,FragPos,FragCharge,FragMZ_round
0,4,1,871.957,113612862,871.957,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,2,872.459,105172507,872.459,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,4,872.962,68061875,872.962,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,7,873.463,26440569,873.463,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,8,863.447,11095406,863.447,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4,9,863.947,9718011,863.947,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,4,11,733.898,22481832,733.898,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,4,15,873.964,6966100,873.964,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,4,17,658.376,4189165,658.376,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,4,19,864.448,5059214,864.448,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,4,21,1185.585,4891505,1185.585,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,4,22,672.371,3622062,672.371,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,4,25,734.413,4693379,734.413,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,4,27,1256.622,4057179,1256.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,4,28,1071.542,3763922,1071.542,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,4,36,1186.588,3119917,1186.588,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,4,38,1172.569,2860109,1172.569,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,4,43,862.953,2620427,862.953,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,4,45,1257.625,2774844,1257.625,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,4,46,1072.545,2265098,1072.545,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,4,47,864.949,2054713,864.949,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,4,48,673.374,1565579,673.374,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,4,51,659.379,1625288,659.379,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,4,52,1173.571,1997664,1173.571,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,4,55,1085.537,1954311,1085.537,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,4,56,1466.757,1960217,1466.757,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,4,59,816.419,1439520,816.419,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,4,61,872.406,2241816,872.406,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,4,62,874.464,1418472,874.464,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,4,66,872.834,1108678,872.834,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
470,4,1891,865.136,14685,865.136,NaN,NaN,NaN,NaN,NaN,NaN,NaN
471,4,1908,673.380,571372,673.380,NaN,NaN,NaN,NaN,NaN,NaN,NaN
472,4,1926,873.228,21137,873.228,NaN,NaN,NaN,NaN,NaN,NaN,NaN
473,4,1928,617.272,12061,617.272,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474,4,1929,571.453,12159,571.453,NaN,NaN,NaN,NaN,NaN,NaN,NaN
475,4,1934,763.888,9908,763.888,NaN,NaN,NaN,NaN,NaN,NaN,NaN
476,4,1937,850.748,13620,850.748,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,4,1945,1185.333,8416,1185.333,NaN,NaN,NaN,NaN,NaN,NaN,NaN
478,4,1959,818.773,8432,818.773,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479,4,1968,1211.581,10698,1211.581,NaN,NaN,NaN,NaN,NaN,NaN,NaN
480,4,1972,898.422,715790,898.422,NaN,NaN,NaN,NaN,NaN,NaN,NaN
481,4,1982,1173.582,693711,1173.582,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,4,1984,772.822,8349,772.822,NaN,NaN,NaN,NaN,NaN,NaN,NaN
483,4,1987,846.443,72167,846.443,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484,4,1988,862.758,20232,862.758,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,4,1994,1239.584,148661,1239.584,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486,4,2006,1562.749,9048,1562.749,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487,4,2020,850.203,18144,850.203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488,4,2026,1146.582,10681,1146.582,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489,4,2028,631.320,6997,631.320,NaN,NaN,NaN,NaN,NaN,NaN,NaN
490,4,2029,685.368,43008,685.368,NaN,NaN,NaN,NaN,NaN,NaN,NaN
491,4,2048,735.216,21903,735.216,NaN,NaN,NaN,NaN,NaN,NaN,NaN
492,4,2060,870.053,12806,870.053,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,4,2064,858.399,23082,858.399,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,4,2066,734.003,11254,734.003,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,4,2075,667.313,9911,667.313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,4,2084,856.951,50984,856.951,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,4,2086,866.091,11757,866.091,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,4,2091,375.361,7230,375.361,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,4,2096,1186.886,17905,1186.886,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
ms2_peaks_msc_fragments_df[ms2_peaks_msc_fragments_df.FragMZ.notnull()]

,feature_id,peak_id,centroid_mz,intensity,centroid_mz_round,FragMZ,FragInt,FragError,FragIonTypes,FragPos,FragCharge,FragMZ_round
8,4,17,658.376,4189165,658.376,658.375977,6.083308e+06,-0.001038,y,6.0,1.0,658.376
10,4,21,1185.585,4891505,1185.585,1185.584961,9.656905e+06,-0.000854,y,11.0,1.0,1185.585
11,4,22,672.371,3622062,672.371,672.370972,5.319180e+06,-0.000549,b,6.0,1.0,672.371
13,4,27,1256.622,4057179,1256.622,1256.621948,8.328303e+06,-0.000977,y,12.0,1.0,1256.622
14,4,28,1071.542,3763922,1071.542,1071.541992,6.934142e+06,-0.000977,y,10.0,1.0,1071.542
16,4,38,1172.569,2860109,1172.569,1172.568970,5.583050e+06,-0.000488,b,11.0,1.0,1172.569
24,4,55,1085.537,1954311,1085.537,1085.536987,3.627584e+06,-0.000488,b,10.0,1.0,1085.537
25,4,56,1466.757,1960217,1466.757,1466.756714,4.746105e+06,-0.003052,y,14.0,1.0,1466.757
32,4,73,900.477,1228935,900.477,900.476990,2.051110e+06,-0.001526,y,8.0,1.0,900.477
35,4,76,729.393,1049764,729.393,729.393005,1.584804e+06,0.000000,b,7.0,1.0,729.393
37,4,79,1014.521,1239494,1014.521,1014.520996,2.201039e+06,-0.000427,y,9.0,1.0,1014.521
39,4,81,843.437,1137086,843.437,843.437012,1.828656e+06,0.001099,b,8.0,1.0,843.437
46,4,89,1369.698,1322676,1369.698,1369.697876,1.210633e+06,-0.009155,y,13.0,1.0,1369.698
47,4,94,1483.717,1114629,1483.717,1483.716675,2.729554e+06,-0.000854,b,14.0,1.0,1483.717
49,4,96,1368.690,1021997,1368.690,1368.689941,2.237517e+06,-0.000732,b,13.0,1.0,1368.690
52,4,101,957.477,843141,957.477,957.476990,1.459208e+06,-0.001892,b,9.0,1.0,957.477
57,4,113,1155.546,856774,1155.546,1155.546021,1.653730e+06,0.003052,b^,11.0,1.0,1155.546
71,4,135,1068.512,547849,1068.512,1068.511963,9.996130e+05,0.001099,b^,10.0,1.0,1068.512
90,4,179,1596.802,529154,1596.802,1596.801758,1.381216e+06,0.000122,b,15.0,1.0,1596.802
120,4,248,1239.598,236842,1239.598,1239.598022,4.238690e+05,0.001587,y^,12.0,1.0,1239.598
122,4,255,1168.561,234306,1168.561,1168.561035,4.570460e+05,0.001709,y^,11.0,1.0,1168.561
136,4,316,1351.665,156679,1351.665,1351.664917,3.137270e+05,0.000854,b^,13.0,1.0,1351.665
159,4,403,1054.518,97825,1054.518,1054.517944,1.781150e+05,0.001587,y^,10.0,1.0,1054.518
164,4,409,1449.730,112752,1449.730,1449.729736,2.408630e+05,-0.003540,y^,14.0,1.0,1449.730
175,4,465,1579.776,81430,1579.776,1579.775757,2.100180e+05,0.000610,b^,15.0,1.0,1579.776
188,4,515,1144.573,50272,1144.573,1144.572998,9.682501e+04,-0.001587,a,11.0,1.0,1144.573
196,4,566,1269.614,73920,1269.614,1269.614014,1.519560e+05,-0.008179,b,12.0,1.0,1269.614
235,4,741,1238.610,40996,1238.610,1238.609985,8.315001e+04,-0.002441,y*,12.0,1.0,1238.610
241,4,767,1057.540,44073,1057.540,1057.540039,8.030301e+04,-0.002441,a,10.0,1.0,1057.540
262,4,860,277.156,744359,277.156,277.156006,8.678230e+05,0.001343,b,2.0,1.0,277.156
265,4,867,260.198,804972,260.198,260.197998,9.366230e+05,0.001129,y,2.0,1.0,260.198
306,4,1068,815.422,1000961,815.422,815.421997,1.589597e+06,0.006775,y,15.0,2.0,815.422
310,4,1080,1251.610,17607,1251.610,1251.609985,3.611601e+04,-0.001709,b*,12.0,1.0,1251.610
325,4,1189,1252.600,23548,1252.600,1252.599976,2.341801e+04,0.004272,b^,12.0,1.0,1252.600
328,4,1199,375.224,1529911,375.224,375.223999,1.898007e+06,0.000183,y,3.0,1.0,375.224
381,4,1455,1350.677,15580,1350.677,1350.676880,3.367502e+04,-0.003174,b*,13.0,1.0,1350.677
411,4,1627,1448.742,15177,1448.742,1448.741699,3.630802e+04,-0.007568,y*,14.0,1.0,1448.742

In [99]:
db_conn = sqlite3.connect(DB_NAME)
feature_list_df = pd.read_sql_query("select * from feature_list", db_conn)
db_conn.close()

In [100]:
feature_list_df.head()

,feature_id,charge_state,monoisotopic_mass,retention_time_secs,isotope_count,cluster_mz_centroid,cluster_summed_intensity,minimum_error,minimum_error_sulphur
0,1,2,1066.606152,590.4,6,534.310352,1985980902,1.647301e-01,0
1,2,3,1928.009933,535.6,7,643.677254,2425291014,7.140533e-06,0
2,3,3,2044.113664,1023.2,7,682.378497,2881543763,1.953337e-07,2
3,4,2,1741.892439,720.6,6,871.953496,1248224845,9.673931e-03,2
4,5,3,1927.994175,536.2,8,643.672001,461668922,1.976963e-05,0

In [102]:
# isolate the feature-level attributes reported by MSC
msc_feature_df = msc_subset_df[["FeatureNum","DiggerPepScore","DeltaMassDa","DeltaMassPPM"]]
msc_feature_df.head()

       FeatureNum  DiggerPepScore  DeltaMassDa  DeltaMassPPM
15158       21928             0.0          0.0           0.0
5484        21927             0.0          0.0           0.0
17443       21926             0.0          0.0           0.0
16605       21925             0.0          0.0           0.0
16592       21924             0.0          0.0           0.0

In [106]:
# annotate the features with the attributes reported by MSC.
# msc_DiggerPepScore of zero or more is what MSC reported. NaN means MSC didn't report the feature at all
feature_list_msc_df = pd.merge(feature_list_df, msc_feature_df, how='left', left_on=['feature_id'], right_on=['FeatureNum'])
feature_list_msc_df.drop(['FeatureNum'], inplace=True, axis=1)
feature_list_msc_df.rename(columns={'DiggerPepScore': 'msc_DiggerPepScore', 'DeltaMassDa': 'msc_DeltaMassDa', 'DeltaMassPPM': 'msc_DeltaMassPPM'}, inplace=True)

In [107]:
feature_list_msc_df.head()

,feature_id,charge_state,monoisotopic_mass,retention_time_secs,isotope_count,cluster_mz_centroid,cluster_summed_intensity,minimum_error,minimum_error_sulphur,msc_DiggerPepScore,msc_DeltaMassDa,msc_DeltaMassPPM
0,1,2,1066.606152,590.4,6,534.310352,1985980902,1.647301e-01,0,0.000,0.000000,0.000
1,2,3,1928.009933,535.6,7,643.677254,2425291014,7.140533e-06,0,29.583,0.009592,4.975
2,3,3,2044.113664,1023.2,7,682.378497,2881543763,1.953337e-07,2,NaN,NaN,NaN
3,4,2,1741.892439,720.6,6,871.953496,1248224845,9.673931e-03,2,320.189,-0.007459,-4.282
4,5,3,1927.994175,536.2,8,643.672001,461668922,1.976963e-05,0,0.000,0.000000,0.000

In [108]:
feature_list_msc_df[feature_list_msc_df.msc_DiggerPepScore >= 0].head()

,feature_id,charge_state,monoisotopic_mass,retention_time_secs,isotope_count,cluster_mz_centroid,cluster_summed_intensity,minimum_error,minimum_error_sulphur,msc_DiggerPepScore,msc_DeltaMassDa,msc_DeltaMassPPM
0,1,2,1066.606152,590.4,6,534.310352,1985980902,0.164730,0,0.000,0.000000,0.000
1,2,3,1928.009933,535.6,7,643.677254,2425291014,0.000007,0,29.583,0.009592,4.975
3,4,2,1741.892439,720.6,6,871.953496,1248224845,0.009674,2,320.189,-0.007459,-4.282
4,5,3,1927.994175,536.2,8,643.672001,461668922,0.000020,0,0.000,0.000000,0.000
9,10,2,986.560834,790.0,6,494.287693,1855507701,0.020531,0,38.209,-0.003978,-4.032