In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import sqlite3
import json
import numpy as np

In [3]:
# EXPERIMENT_DIR = '/home/ubuntu/experiments/dwm-test'
EXPERIMENT_DIR = '/Users/darylwilding-mcbride/Downloads/experiments/dwm-test'

In [4]:
EXTRACTED_FEATURES_DIR = "{}/extracted-features".format(EXPERIMENT_DIR)
EXTRACTED_FEATURES_DB_NAME = "{}/extracted-features.sqlite".format(EXTRACTED_FEATURES_DIR)

In [28]:
db_conn = sqlite3.connect(EXTRACTED_FEATURES_DB_NAME)
sequences_df = pd.read_sql_query('select * from features limit 100', db_conn)
db_conn.close()

In [31]:
sequences_df.sample(5)

,sequence,charge,file_idx,peak_idx,target_coords,theoretical_mz,q_value,delta_mz_ppm,delta_rt,delta_scan,...,monoisotopic_mz_centroid,monoisotopic_mz_delta_ppm,number_of_isotopes,rt_apex,scan_apex,run_name,batch,human,number_of_runs_extracted,isotope_raw_points
42,AADIIGIGINGVDAVSELSK,2,8,0,"{""mono_mz"": 971.5250836990213, ""scan_apex"": 25...",971.528176,0.000003,-0.449273,0.000361,-0.003678,...,971.524479,-0.622161,7,968.142416,256,190719_Hela_Ecoli_1to1_10,1to1,0,7,"[[{'mz': 971.5214391552709, 'scan': 254.0, 'fr..."
16,AAAIGIDLGTTYSCVGVFQHGK,3,8,0,"{""mono_mz"": 755.7161125762381, ""scan_apex"": 59...",755.715897,0.000003,-0.104891,-0.000057,-0.001377,...,755.715971,-0.186777,7,799.843422,593,190719_Hela_Ecoli_1to1_10,1to1,1,10,"[[{'mz': 755.7145782803658, 'scan': 579.0, 'fr..."
78,AAFQPVFLEVVDESYR,2,8,0,"{""mono_mz"": 935.4725283167053, ""scan_apex"": 33...",935.472676,0.000003,2.083067,-0.000440,0.002241,...,935.474392,1.992558,6,1049.241906,333,190719_Hela_Ecoli_1to1_10,1to1,0,10,"[[{'mz': 935.4723060990068, 'scan': 325.0, 'fr..."
91,AAGGLWFGWSGETGNEDQPLK,2,8,0,"{""mono_mz"": 1110.5214778236143, ""scan_apex"": 1...",1110.521426,0.000093,-0.998026,-0.001681,0.006954,...,1110.520157,-1.188943,4,886.123460,136,190719_Hela_Ecoli_1to1_10,1to1,0,10,"[[{'mz': 1110.51811292055, 'scan': 124.0, 'fra..."
18,AAAPAPEEEMDECEQALAAEPK,2,8,0,"{""mono_mz"": 1179.017504490358, ""scan_apex"": 10...",1179.017208,0.000003,-0.073992,0.000014,0.339476,...,1179.017215,-0.245533,7,632.376694,136,190719_Hela_Ecoli_1to1_10,1to1,1,10,"[[{'mz': 1179.01320546183, 'scan': 130.0, 'fra..."

In [32]:
selected_sequence = 'AAFQPVFLEVVDESYR'
selected_sequence_charge = 2

In [37]:
# load all the instances of this sequence across the experiment
db_conn = sqlite3.connect(EXTRACTED_FEATURES_DB_NAME)
selected_sequence_df = pd.read_sql_query('select * from features where sequence==\'{}\' and charge=={}'.format(selected_sequence, selected_sequence_charge), db_conn)
db_conn.close()

In [39]:
# index 4 of isotope_intensities_l is the raw points for each isotope
selected_sequence_df['isotope_raw_points'] = selected_sequence_df.apply(lambda row: [pd.DataFrame(d[4], columns=['mz','scan','frame_id','retention_time_secs','intensity']).to_dict('records') for d in json.loads(row.isotope_intensities_l)], axis=1)

In [40]:
selected_sequence_df

,sequence,charge,file_idx,peak_idx,target_coords,theoretical_mz,q_value,delta_mz_ppm,delta_rt,delta_scan,...,monoisotopic_mz_centroid,monoisotopic_mz_delta_ppm,number_of_isotopes,rt_apex,scan_apex,run_name,batch,human,number_of_runs_extracted,isotope_raw_points
0,AAFQPVFLEVVDESYR,2,8,0,"{""mono_mz"": 935.4725283167053, ""scan_apex"": 33...",935.472676,0.000003,2.083067,-0.000440,0.002241,...,935.474392,1.992558,6,1049.241906,333,190719_Hela_Ecoli_1to1_10,1to1,0,10,"[[{'mz': 935.4723060990068, 'scan': 325.0, 'fr..."
1,AAFQPVFLEVVDESYR,2,15,0,"{""mono_mz"": 935.4724467478961, ""scan_apex"": 32...",935.472676,0.000003,1.877716,0.001433,-0.057991,...,935.474198,1.871830,4,1063.722494,308,190719_Hela_Ecoli_1to1_04,1to1,0,10,"[[{'mz': 935.4722829758884, 'scan': 306.0, 'fr..."
2,AAFQPVFLEVVDESYR,2,6,1,"{""mono_mz"": 935.4724845953756, ""scan_apex"": 32...",935.472676,0.000003,1.848922,0.005501,-0.033969,...,935.474085,1.710433,3,1062.750933,315,190719_Hela_Ecoli_1to1_03,1to1,0,10,"[[{'mz': 935.4722702710349, 'scan': 314.0, 'fr..."
3,AAFQPVFLEVVDESYR,2,19,0,"{""mono_mz"": 935.4723275882084, ""scan_apex"": 32...",935.472676,0.000003,-0.046266,-0.000018,0.001340,...,935.472284,-0.046266,5,1049.508343,327,190719_Hela_Ecoli_1to1_06,1to1,0,10,"[[{'mz': 935.4722843077836, 'scan': 322.0, 'fr..."
4,AAFQPVFLEVVDESYR,2,1,0,"{""mono_mz"": 935.4726066084253, ""scan_apex"": 32...",935.472676,0.000003,1.958189,-0.000191,0.007510,...,935.474504,2.028593,5,1050.461580,331,190719_Hela_Ecoli_1to1_07,1to1,0,10,"[[{'mz': 935.4722485729433, 'scan': 325.0, 'fr..."
5,AAFQPVFLEVVDESYR,2,2,0,"{""mono_mz"": 935.4727198449904, ""scan_apex"": 33...",935.472676,0.000003,1.741750,-0.000345,-0.004230,...,935.474284,1.672047,5,1049.871761,329,190719_Hela_Ecoli_1to1_09,1to1,0,10,"[[{'mz': 935.4722638953049, 'scan': 323.0, 'fr..."
6,AAFQPVFLEVVDESYR,2,10,0,"{""mono_mz"": 935.4726091926835, ""scan_apex"": 32...",935.472676,0.000003,2.088829,-0.000230,0.011878,...,935.474323,1.832084,3,1049.611347,332,190719_Hela_Ecoli_1to1_08,1to1,0,10,"[[{'mz': 935.4723056753493, 'scan': 328.0, 'fr..."
7,AAFQPVFLEVVDESYR,2,18,0,"{""mono_mz"": 935.4726621555569, ""scan_apex"": 32...",935.472676,0.000003,1.545950,0.000202,-0.000730,...,935.474044,1.477306,7,1055.715029,325,190719_Hela_Ecoli_1to1_05,1to1,0,10,"[[{'mz': 935.472275991835, 'scan': 314.0, 'fra..."
8,AAFQPVFLEVVDESYR,2,11,0,"{""mono_mz"": 935.4724439789878, ""scan_apex"": 32...",935.472676,0.000003,1.997979,-0.002684,0.019259,...,935.473995,1.657731,7,1056.772719,330,190719_Hela_Ecoli_1to1_01,1to1,0,10,"[[{'mz': 935.4722838184781, 'scan': 323.0, 'fr..."
9,AAFQPVFLEVVDESYR,2,16,0,"{""mono_mz"": 935.4719154939461, ""scan_apex"": 32...",935.472676,0.000003,-2.120314,-0.002792,-0.003415,...,935.470269,-1.760294,5,1056.191693,324,190719_Hela_Ecoli_1to1_02,1to1,0,10,"[[{'mz': 935.4674532576836, 'scan': 328.0, 'fr..."

In [57]:
isotopes_l = []
for isotope_idx,isotope in enumerate(isotope_raw_points_l):
    isotope_df = pd.DataFrame(isotope)
    # fix up some types
    isotope_df.frame_id = isotope_df.frame_id.astype(int)
    isotope_df.scan = isotope_df.scan.astype(int)
    isotope_df.intensity = isotope_df.intensity.astype(int)
    # keep track of which isotope is which
    isotope_df['isotope_idx'] = isotope_idx
    isotopes_l.append(isotope_df)
# join the list of dataframes into a single dataframe
isotopes_df = pd.concat(isotopes_l, axis=0, sort=False)

In [58]:
isotopes_df

    frame_id  intensity          mz  retention_time_secs  scan  isotope_idx
0       9801        282  935.472306          1048.185483   325            0
1       9826        101  935.472306          1050.826208   325            0
2       9786        105  935.472306          1046.601437   326            0
3       9806        144  935.472306          1048.714169   326            0
4       9821        130  935.472306          1050.298746   326            0
5       9806        265  935.472306          1048.714169   327            0
6       9811        210  935.472306          1049.241906   327            0
7       9821         63  935.472306          1050.298746   327            0
8       9781         21  935.472306          1046.061007   328            0
9       9791         94  935.472306          1047.130328   328            0
10      9801         95  935.472306          1048.185483   328            0
11      9781        164  935.472306          1046.061007   329            0
12      9786         53  935.472306          1046.601437   329            0
13      9801         42  935.472306          1048.185483   329            0
14      9776         58  935.472306          1045.531819   330            0
15      9801         50  935.472306          1048.185483   330            0
16      9806        302  935.472306          1048.714169   330            0
17      9811        166  935.472306          1049.241906   330            0
18      9816        257  935.472306          1049.770641   330            0
19      9821        247  935.472306          1050.298746   330            0
20      9781         42  935.472306          1046.061007   331            0
21      9791        145  935.472306          1047.130328   331            0
22      9831        132  935.472306          1051.354963   331            0
23      9786        137  935.472306          1046.601437   333            0
24      9791        244  935.472306          1047.130328   333            0
25      9796        163  935.472306          1047.657946   333            0
26      9801        193  935.472306          1048.185483   333            0
27      9786         51  935.472306          1046.601437   334            0
28      9796        176  935.472306          1047.657946   334            0
29      9811        367  935.472306          1049.241906   334            0
..       ...        ...         ...                  ...   ...          ...
47      9811         30  936.978947          1049.241906   336            3
48      9831         41  936.978947          1051.354963   337            3
49      9821        108  936.978947          1050.298746   338            3
50      9796         64  936.978947          1047.657946   339            3
51      9811         41  936.978947          1049.241906   340            3
52      9836        113  936.978948          1051.885157   330            3
53      9836         38  936.978948          1051.885157   337            3
54      9881        130  936.978948          1056.670324   336            3
0       9811         73  937.478229          1049.241906   329            4
1       9791         90  937.478229          1047.130328   331            4
2       9816        108  937.478229          1049.770641   331            4
3       9796         12  937.478229          1047.657946   332            4
4       9801        102  937.478229          1048.185483   335            4
5       9791         24  937.478229          1047.130328   337            4
6       9811        132  937.478229          1049.241906   338            4
7       9811         35  937.478229          1049.241906   341            4
8       9806        135  937.483030          1048.714169   329            4
9       9801         37  937.483030          1048.185483   330            4
10      9806         88  937.483030          1048.714169   337            4
11      9811         50  937.483030          1049.241906   340            4
12      9851        131  937.483031          1053.468910   330            4
13      9851         84  937.483031          1053.468910   333            4
14      9871         48  937.483031          1055.601208   335            4
15      9876         68  937.483032          1056.141552   332            4
16      9881         44  937.483032          1056.670324   335            4
0       9866         79  937.982447          1055.073243   325            5
1       9856          9  937.982447          1054.016821   326            5
2       9866         69  937.982447          1055.073243   326            5
3       9876         62  937.982448          1056.141552   326            5
4       9881         89  937.982448          1056.670324   327            5

[360 rows x 6 columns]