In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import sqlite3
import json
import numpy as np

In [2]:
EXPERIMENT_DIR = '/home/ubuntu/experiments/dwm-test'
# EXPERIMENT_DIR = '/Users/darylwilding-mcbride/Downloads/experiments/dwm-test'

In [5]:
EXTRACTED_FEATURES_DIR = "{}/extracted-features".format(EXPERIMENT_DIR)
EXTRACTED_FEATURES_DB_NAME = "{}/extracted-features.sqlite".format(EXTRACTED_FEATURES_DIR)

In [6]:
db_conn = sqlite3.connect(EXTRACTED_FEATURES_DB_NAME)
sequences_df = pd.read_sql_query('select * from features', db_conn)
db_conn.close()

In [7]:
sequences_df.sample(5)

,sequence,charge,file_idx,peak_idx,target_coords,theoretical_mz,q_value,delta_mz_ppm,delta_rt,delta_scan,...,monoisotopic_mass,monoisotopic_mz_centroid,monoisotopic_mz_delta_ppm,number_of_isotopes,rt_apex,scan_apex,run_name,batch,human,number_of_runs_extracted
229467,VVLALACNSLAGIQR,2,16,0,"{""mono_mz"": 792.9482600961882, ""scan_apex"": 33...",792.948158,0.001165,-0.121262,-0.000867,-0.014472,...,1583.881418,792.947985,-0.346641,5,906.276515,329,190719_Hela_Ecoli_1to1_02,1to1,1,10
88981,TRPSSTVIK,2,19,0,"{""mono_mz"": 494.7928270186945, ""scan_apex"": 88...",494.792926,0.000481,-0.110137,-0.002754,0.013339,...,987.570993,494.792773,-0.110137,5,198.507006,901,190719_Hela_Ecoli_1to1_06,1to1,1,10
81679,LPAVSSVACGASVGYAVTK,2,19,0,"{""mono_mz"": 918.9799158453347, ""scan_apex"": 35...",918.979808,0.000003,0.720612,0.001500,0.000984,...,1835.946598,918.980575,0.717474,7,667.887723,356,190719_Hela_Ecoli_1to1_06,1to1,1,10
219337,LHNMIVDLDNVVK,2,16,0,"{""mono_mz"": 755.4076742489962, ""scan_apex"": 46...",755.408326,0.000003,-1.397378,-0.001144,-0.007912,...,1508.798416,755.406484,-1.575866,7,746.638611,462,190719_Hela_Ecoli_1to1_02,1to1,1,10
205611,VSSVPNTSQSYAK,2,11,0,"{""mono_mz"": 684.3438970231606, ""scan_apex"": 66...",684.343726,0.000037,-0.069267,-0.002078,0.008357,...,1366.673719,684.344136,0.348575,5,283.950457,670,190719_Hela_Ecoli_1to1_01,1to1,1,8

In [ ]:
selected_sequence = 'FIQQTYPSGGEEQAQYCR'
selected_sequence_charge = 2

In [ ]:
db_conn = sqlite3.connect(EXTRACTED_FEATURES_DB_NAME)
selected_sequence_df = pd.read_sql_query('select * from features where sequence==\'{}\' and charge=={} order by run_name'.format(selected_sequence,selected_sequence_charge), db_conn)
db_conn.close()

In [ ]:
# unpack the raw points for each isotope for each sequence instance
for row in selected_sequence_df.itertuples():